In [64]:
df = pd.read_csv('C:/Users/Administrator/Downloads/listings.csv')
df = pd.read_csv('C:/Users/Administrator/Downloads/listings.csv')

df1 = pd.read_csv('C:/Users/Administrator/Downloads/my_data.csv')


df=pd.concat([df['review_scores_rating'],df1],axis=1)
df.dropna(inplace=True)

df

,review_scores_rating,host_is_superhost,minimum_nights,price,availability_365,number_of_reviews,distance,instat,instaf,resp_1,resp_2,resp_3,resp_4
0,4.79,0,120,99.0,77,53,0.920530,0,1,1,0,0,0
2,4.97,1,28,90.0,131,59,5.172916,0,1,0,0,1,0
3,4.92,1,3,99.0,65,154,5.029878,0,1,1,0,0,0
4,4.74,1,2,99.0,124,291,3.870129,1,0,1,0,0,0
5,4.97,1,2,106.0,130,165,4.762897,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5667,4.50,0,5,199.0,0,2,0.526037,0,1,1,0,0,0
5669,5.00,0,2,160.0,0,4,1.129761,0,1,0,0,1,0
5670,4.33,0,2,180.0,0,6,8.547629,0,1,0,0,0,0
5672,5.00,0,3,925.0,0,1,4.150300,0,1,0,0,0,0
5674,5.00,1,30,85.0,29,2,2.900828,0,1,1,0,0,0

In [68]:
import pandas as pd
from scipy.stats import mannwhitneyu


superhost = df.loc[df['host_is_superhost'] == 1]
non_superhost = df.loc[df['host_is_superhost'] == 0]

# Loop through columns and perform Mann-Whitney U test
for col in df.columns:
    if col == 'host_is_superhost':
        continue
    p_value = mannwhitneyu(superhost[col], non_superhost[col]).pvalue
    if p_value < 0.05:
        print(f"Column {col} is significantly different between Superhost and non-Superhost (p-value = {p_value})")

Column review_scores_rating is significantly different between Superhost and non-Superhost (p-value = 4.1189763274596155e-44)
Column price is significantly different between Superhost and non-Superhost (p-value = 1.1696739851480125e-05)
Column availability_365 is significantly different between Superhost and non-Superhost (p-value = 1.337717525825477e-17)
Column number_of_reviews is significantly different between Superhost and non-Superhost (p-value = 1.0786011948111488e-112)
Column instat is significantly different between Superhost and non-Superhost (p-value = 7.166490792883544e-09)
Column instaf is significantly different between Superhost and non-Superhost (p-value = 7.166490792883544e-09)
Column resp_1 is significantly different between Superhost and non-Superhost (p-value = 8.116913426595652e-79)

In [71]:
import pandas as pd
from scipy.stats import rankdata

def cliffs_delta(lst1, lst2):
    """Function to calculate Cliff's Delta"""
    m, n = len(lst1), len(lst2)
    lst1 = sorted(lst1)
    lst2 = sorted(lst2)
    j, k = 0, 0
    res = 0
    while j < m and k < n:
        if lst1[j] <= lst2[k]:
            j += 1
        elif lst1[j] > lst2[k]:
            res += m - j
            k += 1
    return res / (m * n)



superhost = df[df['host_is_superhost'] == 1]
non_superhost = df[df['host_is_superhost'] == 1]

# Loop through columns and calculate Cliff's Delta
for col in df.columns:
    if col == 'host_is_superhost':
        continue

    delta = cliffs_delta(superhost[col], non_superhost[col])
    if delta > 0.147:
        print(f"Column {col} has a large effect size (Cliff's Delta = {delta})")
    elif delta > 0.33:
        print(f"Column {col} has a very large effect size (Cliff's Delta = {delta})")
    elif delta > 0.474:
        print(f"Column {col} has an extremely large effect size (Cliff's Delta = {delta})")

Column review_scores_rating has a large effect size (Cliff's Delta = 0.4642452134534885)
Column minimum_nights has a large effect size (Cliff's Delta = 0.40582209961913546)
Column price has a large effect size (Cliff's Delta = 0.4965191012872642)
Column availability_365 has a large effect size (Cliff's Delta = 0.49641116871090185)
Column number_of_reviews has a large effect size (Cliff's Delta = 0.4950662527593738)
Column distance has a large effect size (Cliff's Delta = 0.49972285605392064)
Column resp_1 has a large effect size (Cliff's Delta = 0.17287288730756778)

In [66]:
def test_significance(col):
    if col.name == 'host_is_superhost':
        return None
    p_value = mannwhitneyu(superhost[col.name], non_superhost[col.name]).pvalue
    if p_value < 0.05:
        return f"Column {col.name} is significantly different between Superhost and non-Superhost (p-value = {p_value})"
    else:
        return None

results = df.apply(test_significance)
results.dropna(inplace=True)
print(results)

ValueError: `x` and `y` must be of nonzero size.

In [67]:
df

,review_scores_rating,host_is_superhost,minimum_nights,price,availability_365,number_of_reviews,distance,instat,instaf,resp_1,resp_2,resp_3,resp_4
0,4.79,0,120,99.0,77,53,0.920530,0,1,1,0,0,0
2,4.97,1,28,90.0,131,59,5.172916,0,1,0,0,1,0
3,4.92,1,3,99.0,65,154,5.029878,0,1,1,0,0,0
4,4.74,1,2,99.0,124,291,3.870129,1,0,1,0,0,0
5,4.97,1,2,106.0,130,165,4.762897,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5667,4.50,0,5,199.0,0,2,0.526037,0,1,1,0,0,0
5669,5.00,0,2,160.0,0,4,1.129761,0,1,0,0,1,0
5670,4.33,0,2,180.0,0,6,8.547629,0,1,0,0,0,0
5672,5.00,0,3,925.0,0,1,4.150300,0,1,0,0,0,0
5674,5.00,1,30,85.0,29,2,2.900828,0,1,1,0,0,0